version: '3.8'

services:
  weak-app:
    build: ./WeakApp  
    container_name: weak-app
    ports:
      - "8081:8080" 
    networks:
      - app-network

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672" 
  #     - "15672:15672" 
  #   networks:
  #     - app-network

  ingestor-service:
    build: ./Catcher
    environment:
      - ApiUrl=http://weak-app:8080
      - ApiKey=supersecret
    depends_on:
      - weak-app
      # - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge